# Generated by Django 3.1.5 on 2021-01-05 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('is_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Note_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_genre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveSmallIntegerField()),
                ('rating', models.FloatField(default=3.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('issue_year', models.PositiveSmallIntegerField(blank=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=2048)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('video_url', models.CharField(blank=True, max_length=2048)),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoview.people')),
                ('relevant_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoview.video')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoview.tag')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoview.video')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoview.note')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoview.video')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoview.people')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoview.video')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoview.note_author'),
        ),
    ]
