# Generated by Django 3.1.5 on 2021-01-05 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinoview', '0002_auto_20210105_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='producer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kinoview.people'),
        ),
        migrations.AlterField(
            model_name='video',
            name='relevant_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kinoview.video'),
        ),
    ]
